-- Migration 0014: split frigate_api_base into two distinct fields
-- =============================================================================
-- `frigate_api_base` conflated two different services:
--   - go2rtc REST API (:1984) — for MSE/WebRTC/frame proxy of frigate-served cameras
--   - Frigate HTTP API (:5000) — for detection event snapshots and backfill
--
-- A single field cannot correctly represent both when an operator runs BYO-Frigate
-- with separate addresses for each service (common: internal docker network names
-- differ). This migration adds the two explicit columns, backfills from the old
-- field where the new ones are empty, and extends the status check constraint on
-- storage_migrations to include 'cancelled' (for #9/#10 migration control plane).
--
-- All DDL is additive and idempotent (ADD COLUMN IF NOT EXISTS / ON CONFLICT DO
-- NOTHING). Safe to apply to the live crumbvms production DB.
-- No explicit BEGIN/COMMIT — run_migrations() uses batch_execute() (one implicit txn).
-- =============================================================================

-- ── server_settings: two new API base columns ─────────────────────────────────
ALTER TABLE server_settings
    ADD COLUMN IF NOT EXISTS frigate_go2rtc_api_base text NOT NULL DEFAULT '';
ALTER TABLE server_settings
    ADD COLUMN IF NOT EXISTS frigate_http_api_base text NOT NULL DEFAULT '';

-- Backfill both new columns from the old `frigate_api_base` where they are empty.
-- Existing installs that had one URL for both services get that URL in both new
-- columns; operators can then correct the Frigate HTTP API field to :5000 as needed.
UPDATE server_settings
    SET frigate_go2rtc_api_base = frigate_api_base
WHERE frigate_go2rtc_api_base = ''
  AND frigate_api_base <> '';

UPDATE server_settings
    SET frigate_http_api_base = frigate_api_base
WHERE frigate_http_api_base = ''
  AND frigate_api_base <> '';

-- ── served_by backfill fix (re-run with host-match heuristic) ────────────────
-- Migration 0012 used a bare port-substring match ('%:8554/%'), which incorrectly
-- classifies cameras whose absolute source URL contains the INTERNAL docker
-- address `go2rtc:8554` (Crumb's own restreamer) as `frigate`-served.
--
-- The corrected heuristic: only classify as 'frigate' when the main_url contains
-- ':8554/' AND the host is NOT 'go2rtc' (the well-known Crumb docker service name).
-- This is additive — it only fixes rows that are currently mis-tagged 'frigate'
-- but whose URL points at the internal go2rtc host.
UPDATE cameras
    SET served_by = 'crumb'
WHERE served_by = 'frigate'
  AND main_url ~ '^rtsp://go2rtc(:[0-9]+)?/';

-- ── storage_migrations: add 'cancelled' to the status check constraint ────────
-- ALTER TABLE ... ALTER COLUMN ... SET CHECK is not directly supported in Postgres;
-- we must DROP the old check and ADD the new one. The constraint name was auto-
-- generated by Postgres from the CREATE TABLE in ensure_storage_migrations_table;
-- we use a DO $$ block to drop it by a known catalog query so it is safe even if
-- the table doesn't exist yet or the constraint has a different auto-generated name.
DO $$
DECLARE
    v_conname text;
BEGIN
    SELECT c.conname INTO v_conname
    FROM pg_constraint c
    JOIN pg_class t ON t.oid = c.conrelid
    JOIN pg_namespace nsp ON nsp.oid = t.relnamespace
    WHERE t.relname = 'storage_migrations'
      AND nsp.nspname = current_schema()
      AND c.contype = 'c'
      AND pg_get_constraintdef(c.oid) LIKE '%pending%'
      AND pg_get_constraintdef(c.oid) LIKE '%running%'
    LIMIT 1;

    IF v_conname IS NOT NULL THEN
        EXECUTE format('ALTER TABLE storage_migrations DROP CONSTRAINT %I', v_conname);
    END IF;
END $$;

-- Only add the new constraint if the table exists.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = current_schema()
          AND table_name = 'storage_migrations'
    ) THEN
        ALTER TABLE storage_migrations
            ADD CONSTRAINT storage_migrations_status_check
            CHECK (status IN ('pending', 'running', 'done', 'failed', 'cancelled'));
    END IF;
END $$;

-- ── segments: per-camera + start_ts index for camera_last_segment (#12) ───────
-- camera_last_segment() does ORDER BY start_ts DESC LIMIT 1 per camera.
-- The existing (camera_id, stream, start_ts) unique index covers per-camera+stream
-- but requires a stream filter; this looser index covers the any-stream case and
-- supports the DESC scan directly.
CREATE INDEX IF NOT EXISTS segments_camera_start_ts
    ON segments (camera_id, start_ts DESC);
