// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Sample the client host's CPU/memory (winapi) + GPU (NVML, best-effort).
///
/// Async so frb runs it on a worker thread - the eventual real core will do
/// blocking NVML/winapi work and we want the poll off the UI isolate from day one.
Future<HostStats> hostStats() => RustLib.instance.api.crateApiHostHostStats();

/// Host-level telemetry for the performance HUD. Cumulative counters
/// (`cpu_time_secs`) are turned into rates by the Dart side from deltas between
/// polls; the rest are instantaneous.
class HostStats {
  final double cpuTimeSecs;
  final double memMb;
  final int numCpus;
  final double? gpuUtil;
  final double? gpuDecUtil;
  final double? gpuMemMb;
  final double? gpuMemTotalMb;
  final String? gpuName;

  const HostStats({
    required this.cpuTimeSecs,
    required this.memMb,
    required this.numCpus,
    this.gpuUtil,
    this.gpuDecUtil,
    this.gpuMemMb,
    this.gpuMemTotalMb,
    this.gpuName,
  });

  @override
  int get hashCode =>
      cpuTimeSecs.hashCode ^
      memMb.hashCode ^
      numCpus.hashCode ^
      gpuUtil.hashCode ^
      gpuDecUtil.hashCode ^
      gpuMemMb.hashCode ^
      gpuMemTotalMb.hashCode ^
      gpuName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HostStats &&
          runtimeType == other.runtimeType &&
          cpuTimeSecs == other.cpuTimeSecs &&
          memMb == other.memMb &&
          numCpus == other.numCpus &&
          gpuUtil == other.gpuUtil &&
          gpuDecUtil == other.gpuDecUtil &&
          gpuMemMb == other.gpuMemMb &&
          gpuMemTotalMb == other.gpuMemTotalMb &&
          gpuName == other.gpuName;
}
