// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dpapi_protect`, `dpapi_unprotect`, `session_path`

/// Encrypt `data` (a JSON session blob) with DPAPI and write it to the session
/// file, replacing any previous one.
Future<void> saveSession({required String data}) =>
    RustLib.instance.api.crateApiSecretSaveSession(data: data);

/// Read + decrypt the saved session, or `None` if there is none / it can't be
/// decrypted (wrong user, corrupt, or not present). Never errors — a bad or
/// missing session just means "not logged in".
Future<String?> loadSession() =>
    RustLib.instance.api.crateApiSecretLoadSession();

/// Delete the saved session (logout / auth failure).
Future<void> clearSession() =>
    RustLib.instance.api.crateApiSecretClearSession();
