//! P0 spike: prove flutter_rust_bridge marshals a real, non-trivial struct out of
//! the kind of Windows-native Rust the desktop client already ships. This is a
//! faithful port of `apps/desktop/src-tauri/src/lib.rs::host_stats` (the perf-HUD
//! host telemetry) with the Tauri command wrapper stripped off — exactly the
//! "extract the pure core, drop the Tauri shell" shape every later phase needs.
//!
//! It samples the client process's CPU time + working-set memory via the Win32
//! API. GPU + decode utilisation are best-effort and vendor-neutral: NVIDIA via
//! NVML when present, otherwise the Windows "GPU Engine" performance counters
//! (`\GPU Engine(*)\Utilization Percentage`), which cover Intel/AMD/NVIDIA. All
//! `None` when neither path is available. The Dart mirror type is generated by
//! frb_codegen.

/// Host-level telemetry for the performance HUD. Cumulative counters
/// (`cpu_time_secs`) are turned into rates by the Dart side from deltas between
/// polls; the rest are instantaneous.
pub struct HostStats {
    pub cpu_time_secs: f64,
    pub mem_mb: f64,
    pub num_cpus: u32,
    pub gpu_util: Option<f64>,
    pub gpu_dec_util: Option<f64>,
    pub gpu_mem_mb: Option<f64>,
    pub gpu_mem_total_mb: Option<f64>,
    pub gpu_name: Option<String>,
}

/// Sample the client host's CPU/memory (winapi) + GPU (NVML, best-effort).
///
/// Async so frb runs it on a worker thread - the eventual real core will do
/// blocking NVML/winapi work and we want the poll off the UI isolate from day one.
pub fn host_stats() -> HostStats {
    let mut s = HostStats {
        cpu_time_secs: 0.0,
        mem_mb: 0.0,
        num_cpus: std::thread::available_parallelism()
            .map(|n| n.get() as u32)
            .unwrap_or(1),
        gpu_util: None,
        gpu_dec_util: None,
        gpu_mem_mb: None,
        gpu_mem_total_mb: None,
        gpu_name: None,
    };

    #[cfg(windows)]
    unsafe {
        use winapi::shared::minwindef::FILETIME;
        use winapi::um::processthreadsapi::{GetCurrentProcess, GetProcessTimes};
        use winapi::um::psapi::{GetProcessMemoryInfo, PROCESS_MEMORY_COUNTERS};

        let proc = GetCurrentProcess();
        let zero = FILETIME {
            dwLowDateTime: 0,
            dwHighDateTime: 0,
        };
        let (mut creation, mut exit, mut kernel, mut user) = (zero, zero, zero, zero);
        if GetProcessTimes(proc, &mut creation, &mut exit, &mut kernel, &mut user) != 0 {
            let to_u64 =
                |ft: FILETIME| (u64::from(ft.dwHighDateTime) << 32) | u64::from(ft.dwLowDateTime);
            // kernel + user time, in 100 ns units → seconds.
            s.cpu_time_secs = (to_u64(kernel) + to_u64(user)) as f64 / 1e7;
        }
        let mut pmc: PROCESS_MEMORY_COUNTERS = std::mem::zeroed();
        pmc.cb = std::mem::size_of::<PROCESS_MEMORY_COUNTERS>() as u32;
        if GetProcessMemoryInfo(proc, &mut pmc, pmc.cb) != 0 {
            s.mem_mb = pmc.WorkingSetSize as f64 / 1e6;
        }
    }

    if let Some(nvml) = NVML.as_ref() {
        if let Ok(dev) = nvml.device_by_index(0) {
            if let Ok(u) = dev.utilization_rates() {
                s.gpu_util = Some(f64::from(u.gpu));
            }
            if let Ok(d) = dev.decoder_utilization() {
                s.gpu_dec_util = Some(f64::from(d.utilization));
            }
            if let Ok(m) = dev.memory_info() {
                s.gpu_mem_mb = Some(m.used as f64 / 1e6);
                s.gpu_mem_total_mb = Some(m.total as f64 / 1e6);
            }
            if let Ok(n) = dev.name() {
                s.gpu_name = Some(n);
            }
        }
    }

    // Vendor-neutral fallback (Intel/AMD, or NVIDIA without NVML): the Windows
    // "GPU Engine" perf counters. Only fills what NVML didn't — never overrides
    // a real NVML reading. Best-effort: any failure leaves the fields None.
    #[cfg(windows)]
    if s.gpu_util.is_none() || s.gpu_dec_util.is_none() {
        if let Some((gpu, decode)) = gpu_engine_utilization() {
            if s.gpu_util.is_none() {
                s.gpu_util = Some(gpu);
            }
            if s.gpu_dec_util.is_none() {
                s.gpu_dec_util = Some(decode);
            }
        }
    }

    s
}

/// Sample the Windows "GPU Engine" performance counters and return
/// `(overall_gpu_pct, decode_pct)` — vendor-neutral (Intel/AMD/NVIDIA).
///
/// Percentage counters need two samples over an interval, so this opens a
/// throw-away query, collects, sleeps briefly, collects again, and formats the
/// wildcard `\GPU Engine(*)\Utilization Percentage` instance array. Instance
/// names look like `pid_1234_..._engtype_3D`; utilisation is summed per engine
/// class (3D/Graphics → overall GPU, VideoDecode → decode) and capped at 100
/// (summing across the per-process/physical engine instances can exceed 100).
///
/// Entirely best-effort: every fallible step maps to `None`, so a wrong path,
/// a missing counter, or a driver that doesn't publish these returns `None` and
/// the HUD shows "—" — it can never break the HUD or panic.
#[cfg(windows)]
fn gpu_engine_utilization() -> Option<(f64, f64)> {
    use std::ptr;
    use winapi::shared::minwindef::DWORD;
    use winapi::um::pdh::{
        PdhAddEnglishCounterW, PdhCloseQuery, PdhCollectQueryData, PdhGetFormattedCounterArrayW,
        PdhOpenQueryW, PDH_FMT_COUNTERVALUE_ITEM_W, PDH_HCOUNTER, PDH_HQUERY,
    };

    // Local constants to avoid depending on winapi exposing them by name.
    const PDH_FMT_DOUBLE: DWORD = 0x0000_0200;
    const PDH_MORE_DATA: i32 = 0x8000_07D2u32 as i32;
    const ERROR_SUCCESS: i32 = 0;

    fn wide(s: &str) -> Vec<u16> {
        s.encode_utf16().chain(std::iter::once(0)).collect()
    }

    unsafe {
        let mut query: PDH_HQUERY = ptr::null_mut();
        if PdhOpenQueryW(ptr::null(), 0, &mut query) != ERROR_SUCCESS {
            return None;
        }
        // RAII-ish guard so every early return closes the query.
        struct QueryGuard(PDH_HQUERY);
        impl Drop for QueryGuard {
            fn drop(&mut self) {
                unsafe {
                    PdhCloseQuery(self.0);
                }
            }
        }
        let _guard = QueryGuard(query);

        let path = wide("\\GPU Engine(*)\\Utilization Percentage");
        let mut counter: PDH_HCOUNTER = ptr::null_mut();
        if PdhAddEnglishCounterW(query, path.as_ptr(), 0, &mut counter) != ERROR_SUCCESS {
            return None;
        }

        // Two samples over a short interval — percentage counters are a delta.
        if PdhCollectQueryData(query) != ERROR_SUCCESS {
            return None;
        }
        std::thread::sleep(std::time::Duration::from_millis(100));
        if PdhCollectQueryData(query) != ERROR_SUCCESS {
            return None;
        }

        // First call sizes the buffer; second fills it.
        let mut buf_size: DWORD = 0;
        let mut item_count: DWORD = 0;
        let rc = PdhGetFormattedCounterArrayW(
            counter,
            PDH_FMT_DOUBLE,
            &mut buf_size,
            &mut item_count,
            ptr::null_mut(),
        );
        if rc != PDH_MORE_DATA || buf_size == 0 {
            return None;
        }

        let mut bytes: Vec<u8> = vec![0u8; buf_size as usize];
        let items = bytes.as_mut_ptr() as *mut PDH_FMT_COUNTERVALUE_ITEM_W;
        if PdhGetFormattedCounterArrayW(
            counter,
            PDH_FMT_DOUBLE,
            &mut buf_size,
            &mut item_count,
            items,
        ) != ERROR_SUCCESS
        {
            return None;
        }

        let mut gpu = 0.0f64;
        let mut decode = 0.0f64;
        for i in 0..item_count as isize {
            let item = &*items.offset(i);
            // Instance name (wide, NUL-terminated).
            let mut name = String::new();
            if !item.szName.is_null() {
                let mut p = item.szName;
                while *p != 0 {
                    name.push(char::from_u32(u32::from(*p)).unwrap_or('?'));
                    p = p.add(1);
                }
            }
            let val = *item.FmtValue.u.doubleValue();
            if !val.is_finite() || val <= 0.0 {
                continue;
            }
            if name.contains("engtype_VideoDecode") {
                decode += val;
            }
            if name.contains("engtype_3D") || name.contains("engtype_Graphics") {
                gpu += val;
            }
        }
        Some((gpu.clamp(0.0, 100.0), decode.clamp(0.0, 100.0)))
    }
}

/// NVML handle, initialised once (loads `nvml.dll` at runtime via libloading).
/// `None` when no NVIDIA driver/GPU is present — the HUD shows "—" for GPU.
static NVML: std::sync::LazyLock<Option<nvml_wrapper::Nvml>> =
    std::sync::LazyLock::new(|| nvml_wrapper::Nvml::init().ok());
