//! P0 spike: prove flutter_rust_bridge marshals a real, non-trivial struct out of
//! the kind of Windows-native Rust the desktop client already ships. This is a
//! faithful port of `apps/desktop/src-tauri/src/lib.rs::host_stats` (the perf-HUD
//! host telemetry) with the Tauri command wrapper stripped off — exactly the
//! "extract the pure core, drop the Tauri shell" shape every later phase needs.
//!
//! It samples the client process's CPU time + working-set memory via the Win32
//! API and best-effort NVIDIA GPU utilisation via NVML (all `None` on a
//! non-NVIDIA host). The Dart mirror type is generated by frb_codegen.

/// Host-level telemetry for the performance HUD. Cumulative counters
/// (`cpu_time_secs`) are turned into rates by the Dart side from deltas between
/// polls; the rest are instantaneous.
pub struct HostStats {
    pub cpu_time_secs: f64,
    pub mem_mb: f64,
    pub num_cpus: u32,
    pub gpu_util: Option<f64>,
    pub gpu_dec_util: Option<f64>,
    pub gpu_mem_mb: Option<f64>,
    pub gpu_mem_total_mb: Option<f64>,
    pub gpu_name: Option<String>,
}

/// Sample the client host's CPU/memory (winapi) + GPU (NVML, best-effort).
///
/// Async so frb runs it on a worker thread - the eventual real core will do
/// blocking NVML/winapi work and we want the poll off the UI isolate from day one.
pub fn host_stats() -> HostStats {
    let mut s = HostStats {
        cpu_time_secs: 0.0,
        mem_mb: 0.0,
        num_cpus: std::thread::available_parallelism()
            .map(|n| n.get() as u32)
            .unwrap_or(1),
        gpu_util: None,
        gpu_dec_util: None,
        gpu_mem_mb: None,
        gpu_mem_total_mb: None,
        gpu_name: None,
    };

    #[cfg(windows)]
    unsafe {
        use winapi::shared::minwindef::FILETIME;
        use winapi::um::processthreadsapi::{GetCurrentProcess, GetProcessTimes};
        use winapi::um::psapi::{GetProcessMemoryInfo, PROCESS_MEMORY_COUNTERS};

        let proc = GetCurrentProcess();
        let zero = FILETIME {
            dwLowDateTime: 0,
            dwHighDateTime: 0,
        };
        let (mut creation, mut exit, mut kernel, mut user) = (zero, zero, zero, zero);
        if GetProcessTimes(proc, &mut creation, &mut exit, &mut kernel, &mut user) != 0 {
            let to_u64 =
                |ft: FILETIME| (u64::from(ft.dwHighDateTime) << 32) | u64::from(ft.dwLowDateTime);
            // kernel + user time, in 100 ns units → seconds.
            s.cpu_time_secs = (to_u64(kernel) + to_u64(user)) as f64 / 1e7;
        }
        let mut pmc: PROCESS_MEMORY_COUNTERS = std::mem::zeroed();
        pmc.cb = std::mem::size_of::<PROCESS_MEMORY_COUNTERS>() as u32;
        if GetProcessMemoryInfo(proc, &mut pmc, pmc.cb) != 0 {
            s.mem_mb = pmc.WorkingSetSize as f64 / 1e6;
        }
    }

    if let Some(nvml) = NVML.as_ref() {
        if let Ok(dev) = nvml.device_by_index(0) {
            if let Ok(u) = dev.utilization_rates() {
                s.gpu_util = Some(f64::from(u.gpu));
            }
            if let Ok(d) = dev.decoder_utilization() {
                s.gpu_dec_util = Some(f64::from(d.utilization));
            }
            if let Ok(m) = dev.memory_info() {
                s.gpu_mem_mb = Some(m.used as f64 / 1e6);
                s.gpu_mem_total_mb = Some(m.total as f64 / 1e6);
            }
            if let Ok(n) = dev.name() {
                s.gpu_name = Some(n);
            }
        }
    }

    s
}

/// NVML handle, initialised once (loads `nvml.dll` at runtime via libloading).
/// `None` when no NVIDIA driver/GPU is present — the HUD shows "—" for GPU.
static NVML: std::sync::LazyLock<Option<nvml_wrapper::Nvml>> =
    std::sync::LazyLock::new(|| nvml_wrapper::Nvml::init().ok());
